### ISSUE TITLE
streaming aborts at start

### ISSUE THREAD

**Issue by pillepalle123** [moonlight-stream/moonlight-embedded#25]
Hi,
any one who knows what the problem is. Trying to stream to my rasbmc, so I first exit xbmc, start the pairing (which works fine), and then start limelight. For a second I can see the streaming-menu at my raspberry pi, then it is gone.

this is what I get:

pi@raspbmc:~$ sudo initctl stop xbmc
xbmc stop/waiting
pi@raspbmc:~$ sudo su
root@raspbmc:/home/pi# java -jar limelight-pi.jar -pair 192.168.0.24
pair Already paired
root@raspbmc:/home/pi# java -jar limelight-pi.jar -720 -30fps 192.168.0.24
Starting app
Jul 09, 2014 7:22:49 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
Jul 09, 2014 7:22:57 PM com.limelight.LimeLog info
INFO: Launched new game session
Starting RTSP handshake
Starting control connection
Starting video stream
Starting audio stream
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM default
java.lang.IllegalStateException: Alsa renderer initialization failure: -2
        at com.limelight.binding.audio.AlsaAudioRenderer.streamInitialized(UnknownSource)
        at com.limelight.nvstream.av.audio.AudioStream.setupAudio(Unknown Source)
        at com.limelight.nvstream.av.audio.AudioStream.startAudioStream(UnknownSource)
        at com.limelight.nvstream.NvConnection.startAudioStream(Unknown Source)
        at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
        at com.limelight.nvstream.NvConnection.access$300(Unknown Source)
        at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:744)
Alsa renderer initialization failure: -2
java: pcm.c:1117: snd_pcm_drain: Assertion `pcm' failed.
Aborted
root@raspbmc:/home/pi# ALSA lib confmisc.c:768:(parse_card) cannot find card '0'^C
root@raspbmc:/home/pi# pi@raspbmc:~$ sudo initctl stop xbmc

thx a lot

**Comment by LaLeLiLeyLu** [comment]
faced the same issue -> sudo modprobe snd-bcm2835 and cat /proc/asound/cards ! you saved my day and now after GFE 2.2.2.0 fix you saved my week ;)
