### ISSUE TITLE
XBOX 360 Rumble

### ISSUE THREAD

**Issue by 4noxx** [moonlight-stream/moonlight-embedded#473]
i read here, that Rumble isnt supported by moonlight. 
in nvidia forum i read this here
https://forums.geforce.com/default/topic/986769/gamestream-rumble-feedback-on-original-shield-controller-/?offset=6

https://forums.geforce.com/default/topic/991412/geforce-now/shield-controller-vibration-rumble-support/

is it possible to use rumble with a xbox 360 controller?

**Comment by irtimmer** [comment]
This isn't yet supported as the details of the protocol for rumbling are currently unknown

**Comment by noxx2015** [comment]
thx, i must switch to SteamOS after Moonlight will not run on LibreELEC (x64). not so nice as Moonlight, but better as nothing.

**Comment by posti85** [comment]
Is it still unsupported? Just to know. Best regards and thank you very much for this amazing project.

**Comment by posti85** [comment]
> This isn't yet supported as the details of the protocol for rumbling are currently unknown

Now there are news on this :) https://github.com/moonlight-stream/moonlight-common-c/commit/fa86e76978e4376afe94b13b64e94b4846f85f02

**Comment by posti85** [comment]
Hi @irtimmer, I've tested the project with the lastest commits about rumble support, but in my xbox 360 wireless controller the rumble feature still doesn't work. That make sense?

**Comment by posti85** [comment]
Can confirm with `sdl2-jstest -r 0` (https://gitlab.com/sdl-jstest/sdl-jstest) that vibration is working properly with the current xpad driver. I've also seen 'Initial attempt to implement rumble for evdev' in a commit message, so I think you are still developing the feature.

**Comment by posti85** [comment]
I've been playing with my recent fixes about the rumble support (https://github.com/irtimmer/moonlight-embedded/pull/740) and for me it is working in xbox 360 controllers.

**Comment by cgutman** [comment]
Fixed
