### ISSUE TITLE
Stream not launching

### ISSUE THREAD

**Issue by ItsVince123** [moonlight-stream/moonlight-embedded#580]
Please provide the following info.

**NVidia Geforce Experience version:** 3.10
**Moonlight Embedded version:** 2.4.3
**Moonlight Embedded source:** GitHub
**Moonlight Embedded running on:** _Raspberry Pi 2 model B
**Moonlight Embedded running on distribution:** Raspbian i think jessie (in berryboot with openelec installed too)

**Verbose output `-verbose` of Moonlight Embedded:**
Searching for server...
Connect to 192.168.2.13...
No mapping available for Logitech USB Keyboard (030000006d0400001cc3000010010000) on /dev/input/event2
No mapping available for Raspberry Pi Sense HAT Joystick (18000000000000000000000000000000) on /dev/input/event3
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Stopping input stream...done
Stopping audio stream...ENet wait interrupted
Control stream connection failed
Loss Stats: Transaction failed: 11
done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done

**What is the expected result?**
Just that the stream starts and i can play
**What happens instead of that?**
It stops locks by 
Stopping input stream...done
 i just stay in raspbian, and i cant move my mouse anymore, so i need to press Ctrl+Alt+Shift+Q

**Extra information**
I used a fix from #568 / #549

**Comment by cgutman** [comment]
Reopen if this is still a problem with the latest builds.
