### ISSUE TITLE
Rock Candy XboX 360 not recognized

### ISSUE THREAD

**Issue by Omnija** [moonlight-stream/moonlight-embedded#587]
Latest Nvidia Experience and Drivers
Latest Version Public Release
Obtained through Script and now updated through apt-get
Raspberry pi 2
Raspbian/Retropie

When booting up it mentions there is no input for event 1 and 2 (Rock Candy xbox 360) naming it with an id of 000000000000000000. I've also manually attempted at editing the controller database to include it but with out success, The input by default is not correct for the controller. I've also tried to manually configure a controller.map but then there is no input at all.

**Comment by cgutman** [comment]
Reopen if this still affects v2.5.0
