### ISSUE TITLE
windows shortcuts not working

### ISSUE THREAD

**Issue by saidbet** [moonlight-stream/moonlight-embedded#613]
Nvidia version: 3.12.0.84
Moonlight-Embedded version: 2.4.6
installed from: repository
device: Raspberry Pi3
Os: Raspbian Jessie

-Verbose output:

moonlight stream -fps 60 -1080 -audio local -app mstsc -verbose
Moonlight Embedded 2.4.6 (PI;ALSA;EMBEDDED)
Searching for server...
Connect to 192.168.0.5...
NVIDIA GeForce GTX 780, GFE 3.12.0.84 (gs_04_04_23287129, 7.1.404.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile gamecontrollerdb.txt
Stream 1920 x 1080, 60 fps, 20000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Stopping input stream...done
Stopping audio stream...ENet wait interrupted
Control stream connection failed
Loss Stats: Transaction failed: 11
done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done

**What is the expected result? Alt+Tab, Alt+F4, Windows key, Alt+Esc should be working ?

**What happens instead of that? Nothing happens

I tried with multiple keyboards and multiple keyboard layouts but can't seem to get windows shortcuts working. The windows key does nothing and alt+... combinations don't seem to work.
I managed to get it working by using VirtualHere, but I can't rely on it because I need to use it at work, and I don't have control over the router to forward ports to my Rpi.

**Comment by lambia** [comment]
It seems to be a limitation of Gamestream protocol, or so I heard. But I can't find anything on this topic. Nonetheless I suppose that should be bypassed doing some sort of re-binding of keycodes. Let's wait for cugtman that previously closed a similar [thread ](https://github.com/moonlight-stream/moonlight-android/issues/83#event-676475512)
I also need a solution as hell. Just this fix and moonlight would be THE solution for cloud computing.

**Comment by lambia** [comment]
Yep, but using different keys for alt-tabbing (one of the most used shortcuts) or for win-shortcuts (win-r, win-d, win-arrows) is not as comfy and intuitive as using original keys. Now I'd like to understand what is the limitation. From the application to intercept windows shortcut before it does, or from the protocol to send those specific keycodes. I want to know the limitation, cause both of them are solvable.

**Comment by MakiseKurisu** [comment]
I think we can revisit this issue since in the latest moonlight-qt the system key capture is added.

**Comment by cgutman** [comment]
This is supported now in GFE 3.20 and later.
