### ISSUE TITLE
IPV6 to IPV6 Streaming

### ISSUE THREAD

**Issue by Maas1337** [moonlight-stream/moonlight-embedded#732]
**NVidia Geforce Experience version:**
GFE 3.15.0.164 (gs_04_09_24784787, 7.1.409.0) and 3.16/17

**Moonlight Embedded version:** 
Moonlight Embedded 2.4.7 (PI;ALSA;PULSE;EMBEDDED) 

**Moonlight Embedded source:**
actual release

**Moonlight Embedded running on:**
Raspberry Pi 3b+

**Moonlight Embedded running on distribution:**
Raspbian 9 Stretch

**Verbose output -verbose of Moonlight Embedded:**

pi@raspberrypi:~ $ sudo moonlight stream 2a00:6020:21f7:4f00:XXXX:6f7a:XXXX:3aca... -1080 -app "Rocket League" --verbose 
Moonlight Embedded 2.4.7 (PI;ALSA;PULSE;EMBEDDED) 
Connect to 2a00:6020:21f7:4f00:XXXX:6f7a:XXXX:3aca... 
NVIDIA GeForce RTX 2080 Ti, 
GFE 3.15.0.164 (gs_04_09_24784787, 7.1.409.0) 
Platform Raspberry Pi (Broadcom) 
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt 
Detected Sony Computer Entertainment Wireless Controller (030000004c050000c405000011810000)on /dev/input/event5 as PS4 Controller Detected Sony Computer Entertainment Wireless Controller Touchpad (030000004c050000c405000011810000) 
on /dev/input/event3 as PS4 Controller Failed to open device /dev/input/event4 
Stream 1920 x 1080, 30 fps, 10000 kbps 
Initializing platform...done 
Resolving host name...done 
Starting RTSP handshake...done 
Initializing control stream...done 
Initializing video stream...done 
Initializing audio stream...done 
Initializing input stream...done 
Starting control stream...
RTSP: Failed to connect to UDP port 47999 failed: -1 
Cleaning up input stream...
done Cleaning up audio stream...
done Cleaning up video stream...
done Cleaning up control stream...
done Cleaning up platform...done 
Error: cannot keep up 

**What is the expected result?**
Moonlight streams Rocket League to the raspberry pi

**What happens instead of that?**
Moonlight starts Rocket League on my homeserver and rasbperry pi get black screen (with desktop session it freezes)

**Im connecting from ipv6 network to ipv6 network.**
When im connecting from the network (where my raspi is) with windows 10 pc, it works perfectly.
Only the connection from raspi pi is without function.

I saw this https://github.com/irtimmer/moonlight-embedded/pull/631, maybe it is the same problem?

Please help me 👍 :-)

**Comment by cgutman** [comment]
This is now supported after https://github.com/moonlight-stream/moonlight-embedded/commit/d7f9bc0b25f744a4913c5b6198f4f96e3d85c8bd
