### ISSUE TITLE
Xbox Wireless Controller on Bluetooth not fully mapped

### ISSUE THREAD

**Issue by sascha777** [moonlight-stream/moonlight-embedded#788]
Hi guys,

I am running
`moonlight-embedded-2.4.11-1buster1`
on my PI 3b and connect to my PC running 
`NVIDIA GeForce GTX 750 Ti, GFE 3.20.3.63 (gs_04_22_28196077, 7.1.422.0)`
It connects my Xbox Wireless Controller via Bluetooth
```
Detected Xbox Wireless Controller (050000005e040000fd02000003090000) on /dev/input/event2 as Xbox One Wireless Controller
Detected Xbox Wireless Controller Consumer Control (050000005e040000fd02000003090000) on /dev/input/event3 as Xbox One Wireless Controller
```
which is listed in the gamecontrollerdb.txt and most recently updated.
Also the gamepad was updated to the latest fireware on my pc.

Issue:
The return/back button isn't mapped correctly.
The verbose log on moonlight-embedded shows (on that same button) the following two missing mappings BUT not on pressing the button but a lit later:
```
Unmapped button: 309
Unmapped button: 313
Unmapped button: 314
Unmapped button: 316
```

When connecting the gamepad via USB with bluetooth disabled I get this verbose message
`No mapping available for Microsoft X-Box One S pad (030000005e040000ea02000008040000) on /dev/input/event2`

Expected behaviour:
Back/return button is working properly

I asked the [SDL_GameControllerDB project](https://github.com/gabomdq/SDL_GameControllerDB/issues/340), but we weren't able to solve it.
Any ideas from why the button isn't mapped correctly?

Thanks for your help!

**Comment by Mythandar** [comment]
I haven't tried this with moonlight embedded, but here's a driver for the xbox One S over bluetooth for linux which works really well on the pi.  https://atar-axis.github.io/xpadneo/  May be worth a try.
