### ISSUE TITLE
Raspbian 64bit support

### ISSUE THREAD

**Issue by ethanholz** [moonlight-stream/moonlight-embedded#805]
Please provide the following info.

**_NVidia Geforce Experience version:_**
N/A
**Moonlight Embedded version:**
N/A
**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
Github/Compiled from Source
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
Raspberry Pi 4 8GB
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._
 Latest Raspbian 64bit beta (raspios_arm64-2020-08-24)
**Verbose output `-verbose` of Moonlight Embedded:**
N/A
**What is the expected result?**
N/A
**What happens instead of that?**
N/A

The Raspberry Pi 4 8GB model only runs on a 64bit kernel due to the RAM size. When attempting to compile, this fails at line 174 of CMakeLists.txt. I believe this is due to issues noted: [https://www.raspberrypi.org/forums/viewtopic.php?t=275370](https://www.raspberrypi.org/forums/viewtopic.php?t=275370). May need to make a change to compilation to better find libGLESv2.so .

**Comment by cgutman** [comment]
A Bullseye aarch64 build is now published using custom-built 64-bit MMAL libraries. See https://github.com/cgutman/moonlight-embedded-packaging/commit/0b0291f4c753a96c3ceb16b3ebc45656d3c25b27
