### ISSUE TITLE
Missing ARM64 version of moonlight-embedded

### ISSUE THREAD

**Issue by Darkyere** [moonlight-stream/moonlight-embedded#807]
Please provide the following info.

**_NVidia Geforce Experience version:_**
**Moonlight Embedded version:**
**Moonlight Embedded source:**deb http://archive.itimmer.nl/raspbian/moonlight buster main
**Moonlight Embedded running on:** _Raspberry Pi 4 8 GB
**Moonlight Embedded running on distribution:** Ubuntu Desktop 20.10 ARM64

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?** apt install moonlight-embedded should contain an arm64 package

**What happens instead of that?** missing moonlight-embedded ARM64 package

**Comment by cgutman** [comment]
A Bullseye aarch64 build is now published using custom-built 64-bit MMAL libraries. See https://github.com/cgutman/moonlight-embedded-packaging/commit/0b0291f4c753a96c3ceb16b3ebc45656d3c25b27
