### ISSUE TITLE
make file running into trouble on raspberry pi

### ISSUE THREAD

**Issue by gabemagee** [moonlight-stream/moonlight-embedded#821]
Please provide the following info.

**_NVidia Geforce Experience version: n/a
**Moonlight Embedded version: 2.5.0
**Moonlight Embedded source: repository
**Moonlight Embedded running on: Raspberry Pi
**Moonlight Embedded running on distribution: Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**

The make file is generated after using the command make inside the build folder of the cloned moonlight-embedded repository, following the steps in the wiki

**What happens instead of that?**

This error:

![2021-07-31-020833_2560x1440_scrot](https://user-images.githubusercontent.com/28644746/127735125-0a154743-7cbd-4845-9b68-aa0e5b5e4e57.png)

**Comment by cgutman** [comment]
You're using an outdated version of the moonlight-common-c/enet submodule. The remote was changed in d7f9bc0b25f744a4913c5b6198f4f96e3d85c8bd to point to the upstream moonlight-common-c repo, and that has likely confused your Git client.

You might be able to solve this by `git submodule deinit -f --all` followed by `git submodule update --init --recursive`, or you can just nuke your repo and `git clone --recursive` again.
