### ISSUE TITLE
 http://archive.itimmer.nl/raspbian/moonlight fails on raspian apt update

### ISSUE THREAD

**Issue by heinrich-k** [moonlight-stream/moonlight-embedded#835]
Hi, this is an issue wit the server, where the repository for direct raspian installation is hosted:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used.
GPG error: http://archimmer.nl/raspbian/moonlight stretch InRelease:
Die folgenden Signaturen waren ungültig:
EXPKEYSIG 7A21919831C60452 Iwan Romario Timmer <irtimmer@gmail.co
W: Fehlschlag beim Holen von http://archive.itimmer.nl/raspbian/moonlight/dists/stretch/InRelease
Die folgenden Signaturen waren ungültig: EXPKEYSIG 7A31C60452 Iwan Romario Timmer <irtimmer@gmail.com>

**Comment by cgutman** [comment]
That is the old APT repository. You need to switch to the new Cloudsmith repository to successfully receive updates.

See the latest instructions on https://github.com/moonlight-stream/moonlight-embedded/wiki/Packages
