### ISSUE TITLE
Platform 'auto' not found

### ISSUE THREAD

**Issue by espenol** [moonlight-stream/moonlight-embedded#837]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.24.0.126
**Moonlight Embedded version:** 2.5.2
**Moonlight Embedded source:** Not sure what this means? Installed via the Bullseye command found [here](https://github.com/moonlight-stream/moonlight-embedded/wiki/Packages#additional-required-setup-steps-for-raspbian-bullseye)
**Moonlight Embedded running on:** Raspberry Pi 4 2GB
**Moonlight Embedded running on distribution:** Raspberry Pi OS, headless, Bullseye

**Verbose output `-verbose` of Moonlight Embedded:**
```
pi@raspberrypi:/ $ moonlight stream -verbose
Moonlight Embedded 2.5.2 (CEC;MMAL;ALSA;PULSE;EMBEDDED)
Searching for server...
Connect to 192.168.1.165...
GPU: NVIDIA GeForce RTX 2070, GFE: 3.24.0.126 (gs_04_37_30719632, 7.1.437.0)
Platform Unknown
Platform 'auto' not found

pi@raspberrypi:/ $ moonlight stream -verbose -platform pi
Moonlight Embedded 2.5.2 (CEC;MMAL;ALSA;PULSE;EMBEDDED)
Searching for server...
Connect to 192.168.1.165...
GPU: NVIDIA GeForce RTX 2070, GFE: 3.24.0.126 (gs_04_37_30719632, 7.1.437.0)
Platform Unknown
Platform 'pi' not found
```

**What is the expected result?**
Establish connection to my desktop PC and start streaming to Raspberry Pi connected to TV

**What happens instead of that?**
Nothing, only given the very short error message above.

**Comment by cgutman** [comment]
On Bullseye, you should use `-platform mmal` not `-platform pi`, though the default `auto` should try both. There must be some issue preventing MMAL from working on your device.

Did you do anything else to your `/boot/config.txt` other than the steps there in the wiki?

**Comment by espenol** [comment]
Hello again, I repeated the steps in the wiki and now it seems to work properly. Not sure what went wrong. Thanks a lot for trying to help!
