### ISSUE TITLE
moonlight usage help commands

### ISSUE THREAD

**Issue by Albusaidi30** [moonlight-stream/moonlight-embedded#842]
Hello everyone

i have install moonlight embedded sucssesfully on raspbeary pi 3B+ buster version . i have appliaction installed in my gaming pc which collect all games from different launchers(EX: steam , Epic games , Xbox game pass and orign ) in one place , called playnite . what i need is to run moonlight with playnite instead of steam big picture ..

i have see the moonlight help and [usage instruction](https://github.com/moonlight-stream/moonlight-embedded/wiki/Usage) but i did not understand. so i need help to write best setting commaned line for moonlight .

these steps what i have done:
1. go to NIVIDA Experience and add the playnite program into shield 
2. i run this command `moonlight list` to show the apps
3. the list is shown as 
`connect to 192.168.0.xxx` 
`1. Playnite` 
`2. Steam `

so i tried this command `moonlight stream -1080 -fps 60 -app playnite 192.168.0.xxx `

but did not work :(

so please help me who to write this kind of command , i need to rum moonlight in 1080p and 60 fps with playnite appliaction 
also please give as i giud how to use this help instruction to write a full commaned line 

 thanks

**Comment by Albusaidi30** [comment]
problem solved. 
it was spelling mistake , the p(for playnite) letter was capital in the `moonlight list` but i am writing a small letter :(
so that why it did not work.

**Comment by jgabriel98** [comment]
Good to know!
Could you close the issue now that it's solved?

to keep thing organized :D
