### ISSUE TITLE
is moonlight broken on ambernic devices after gfe update?

### ISSUE THREAD

**Issue by c0pE89** [moonlight-stream/moonlight-embedded#857]
Please provide the following info.

**_NVidia Geforce Experience version:_**
**Moonlight Embedded version:**
**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**

**What happens instead of that?**

**Comment by cgutman** [comment]
Thanks for the report. 20a02acb07c56dfccf842020bb511e3fce57af0d should fix the issue.

Can you confirm that fixes it?

**Comment by cgutman** [comment]
Closing as assumed fixed in v2.5.3
