### ISSUE TITLE
Rockchip platform issue

### ISSUE THREAD

**Issue by GeorgeWang12356** [moonlight-stream/moonlight-embedded#876]
Please provide the following info.

**_NVidia Geforce Experience version:_**   3.27.0.112
**Moonlight Embedded version:** Moonlight Embedded 2.6.0
**Moonlight Embedded source:** github
**Moonlight Embedded running on:** rk3566 2GB
**Moonlight Embedded running on distribution:** buildroot weston wayland
**Verbose output `-verbose` of Moonlight Embedded:**

root@RK356X:~# moonlight pair 10.0.9.93
Connecting to 10.0.9.93...
Please enter the following PIN on the target PC: 1269
Succesfully paired
root@RK356X:~# moonlight stream 10.0.9.93 -debug -viewonly -app mstsc 
Moonlight Embedded 2.6.0 (CEC;ROCKCHIP;SDL;ALSA;PULSE;EMBEDDED)
Connecting to 10.0.9.93...
Request http://10.0.9.93:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=fa0a8662-51d3-4053-ad37-721939be8ba1
Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.27.0.112</GfeVersion><GsVersion>gs_04_50_32193813</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.0.9.93</LocalIP><LocalIPs><Address>10.0.9.93</Address></LocalIPs><LocalIPs><Address>192.168.168.1</Address></LocalIPs><LocalIPs><Address>192.168.157.1</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>737235008</MaxLumaPixelsH264><MaxLumaPixelsHEVC>589622848</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>C354E6EA0DCBEDF8D9FEE79841527EC7985CE1E3E5C7AE77D6F14CE3530DD031</accountId><appversion>7.1.450.0</appversion><currentgame>0</currentgame><gamelistid>7a5e1cf13853d71b8f0c5646ba35ddf3</gamelistid><gputype>NVIDIA GeForce GTX 1050 Ti</gputype><hostname>DESKTOP-FQRGDLT</hostname><mac>D8:BB:C1:10:65:1A</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>a84dedfd-f4f9-4092-925c-24f38a95b6fc</uniqueid></root>

Request https://10.0.9.93:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=0a8d2250-5002-49d1-a2d5-61a98cd9f416
Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.27.0.112</GfeVersion><GsVersion>gs_04_50_32193813</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.0.9.93</LocalIP><LocalIPs><Address>10.0.9.93</Address></LocalIPs><LocalIPs><Address>192.168.168.1</Address></LocalIPs><LocalIPs><Address>192.168.157.1</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>737235008</MaxLumaPixelsH264><MaxLumaPixelsHEVC>589622848</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>1</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>C354E6EA0DCBEDF8D9FEE79841527EC7985CE1E3E5C7AE77D6F14CE3530DD031</accountId><appversion>7.1.450.0</appversion><currentgame>0</currentgame><gamelistid>7a5e1cf13853d71b8f0c5646ba35ddf3</gamelistid><gputype>NVIDIA GeForce GTX 1050 Ti</gputype><hostname>DESKTOP-FQRGDLT</hostname><mac>D8:BB:C1:10:65:1A</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>a84dedfd-f4f9-4092-925c-24f38a95b6fc</uniqueid></root>

GPU: NVIDIA GeForce GTX 1050 Ti, GFE: 3.27.0.112 (gs_04_50_32193813, 7.1.450.0)
Server codec flags: 0xf03
Platform Rockchip VPU
View-only mode enabled, no input will be sent to the host computer
Request https://10.0.9.93:47984/applist?uniqueid=0123456789ABCDEF&uuid=67c5b1d2-ed45-40d8-944e-8f3e3abff279
Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="applist" status_code="200" status_message="OK"><App><AppInstallPath>C:\Windows\System32\</AppInstallPath><AppTitle>mstsc</AppTitle><CmsId></CmsId><Distributor></Distributor><ID>5542304</ID><IsAppCollectorGame>1</IsAppCollectorGame><IsHdrSupported>0</IsHdrSupported><MaxControllersForSingleSession>1</MaxControllersForSingleSession><ShortName>mstsc</ShortName><SupportedSOPS></SupportedSOPS><UniqueId>0</UniqueId><simulateControllers>0</simulateControllers></App></root>

Request https://10.0.9.93:47984/launch?uniqueid=0123456789ABCDEF&uuid=df99d9b2-8b82-4c67-b979-550028767090&appid=5542304&mode=1280x720x60&additionalStates=1&sops=1&rikey=ad7699957bff9281891b80ef0f8edefa&rikeyid=576974888&localAudioPlayMode=0&surroundAudioInfo=196610&remoteControllersBitmap=0&gcmap=0
Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="launch" status_code="200" status_message="OK"><DisplayHeight>720</DisplayHeight><DisplayWidth>1280</DisplayWidth><EnhancedStreamMode>1</EnhancedStreamMode><HdrMode>0</HdrMode><RefreshRate>60</RefreshRate><avkey>ok</avkey><gamesession>24d1eb4e12c051dd6702d7a6af0f7d13</gamesession><rikey>ok</rikey><sessionUrl0>rtsp://10.0.9.93:48010</sessionUrl0><wssignaling>0</wssignaling></root>

Stream 1280 x 720, 60 fps, 10000 kbps
RTSP port: 48010
Initializing platform...done
Resolving host name...done
Initializing audio stream...done
Starting RTSP handshake...Audio port: 48000
Video port: 47998
Control port: 47999
done
Initializing control stream...done
Initializing video stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...Received first audio packet after 0 ms
Initial audio resync period: 500 milliseconds
done
Received first video packet after 0 ms
Property 'COLOR_SPACE' not found
Property 'allm_enable' not found
Property 'Colorspace' not found

**What is the expected result?**
Stream should begin

**What happens instead of that?**
I didn't see any useful related exceptions, the process has been blocking here without successful streaming

**Comment by cgutman** [comment]
Moonlight Embedded is designed to run outside of a desktop environment. In particular, many backends (including Rockchip) require Moonlight to be the DRM master, which doesn't work because Weston is already DRM master.

For running in desktop environments or modern SBCs that support standard V4L2 decoding and OpenGLES rendering APIs, you should use the full features [Moonlight Qt](https://github.com/moonlight-stream/moonlight-qt) client instead.
