### ISSUE TITLE
rotate option not working with rockchip platform

### ISSUE THREAD

**Issue by Z4rc** [moonlight-stream/moonlight-embedded#878]
**_NVidia Geforce Experience version:_** Sunshine 0.21.0
**Moonlight Embedded version:** 2.6.1
**Moonlight Embedded source:** _compiled from source_
**Moonlight Embedded running on:** _Powkiddy x55 (RK3566)_
**Moonlight Embedded running on distribution:** _JELOS_

The `rotate` option is not working when platform is set to `rk`.
Would be great if this would be possible.

**Comment by EmpressFiona** [comment]
Forgive me for bringing this up, but how did you get `rk` working on JELOS in the first place? Every time I tried it just crashes straight away, never mind getting actual output to rotate. I assume it has something to do with you compiling it yourself.
