### ISSUE TITLE
Uninitialized local variable fdindex

### ISSUE THREAD

**Issue by szsam** [moonlight-stream/moonlight-embedded#889]
https://github.com/moonlight-stream/moonlight-embedded/blob/9c0a2f5edee7b0b4055093dfaa13fdf0b8037b32/src/loop.c#L86
`fdindex` may be uninitialized when accessed here.

-----

Please provide the following info.

**_NVidia Geforce Experience version:_**
**Moonlight Embedded version:**
**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**

**What happens instead of that?**

**Comment by cgutman** [comment]
This was already fixed in dc03235a6212dce5a8c8c8f8294e75e7e1677977 (and was only ever reachable if the caller was buggy and invoked `loop_remove_fd()` for an fd that was never passed to `loop_add_fd()`).
